### PR TITLE
add qb passer rating calculation

### PR DESCRIPTION
**Pull request by monstermudder78**

### CODE REVIEW

**Comment by monstermudder78** [comment]
I added `from __future__ import division` to the top of the file, I did a quick search and didn't see any other division that was relying on the standard python2 convention for dividing ints.

**Comment by BurntSushi** [comment]
@monstermudder78 This looks great, thank you. Could you please remove tabs and use 4 space indents? :-) Tabs in Python is blasphemy (and mixing spaces & tabs is a big no-no). Once that's done, I'll merge. :-)

**Comment by monstermudder78** [comment]
So sorry! Changed text editors and didn't fix the settings. I'll get right on it.

**Comment by monstermudder78** [comment]
Hopefully fixing it through github's editor worked, if not let me know.

**Comment by BurntSushi** [comment]
@monstermudder78 Looks much better. FYI, you can make changes locally and push to your `qbrating` branch and they will show up in this PR.

In any case, thank you! I'll pushing out the next release with this change included, `1.2.13`, right now. It should be up in a few minutes.

**Pull request merged**
