### PR TITLE
2015 Playoff schedule & game updates

### PR DESCRIPTION
**Pull request by ochawkeye**

### CODE REVIEW

**Comment by ochawkeye** [comment]
#193 #195 

Just a guess, but think there could be a case where multiple users are ending up accessing a `gamecenter-json` directory that is not where they expect it.
image

**Comment by BurntSushi** [comment]
Interesting. I still have yet to look into those issues closely, hopefully soon. Thanks for the PR!

**Comment by kpelechrinis** [comment]
I still have not figured out this problem.  I have updated to the latest version (1.2.19).  I have also manually downloaded the playoff games for weeks 3 (championship games) and 4 (super bowl).  However, I still get the same error:

g = nflgame.games(2015,week=4,kind="POST")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/nflgame-1.2.19-py2.7.egg/nflgame/__init__.py", line 228, in games
    return list(games_gen(year, week, home, away, kind, started))
TypeError: 'NoneType' object is not utterable

I went and manually inspected the files (2016012400.json.gz, 2016012401.json.gz and 2016020700.json.gz) and when I try to decompress them instead of obtaining the json file I am getting a *json.gz.cpgz which most probably is due to a corrupted original file.  Can you let me know what you think?

**Comment by BurntSushi** [comment]
I don't know yet. Whatever it is, it clearly requires going and looking at the code to see exactly why games aren't being found. I'll get around to doing it myself, but it could be a while.

**Comment by kpelechrinis** [comment]
Sure; I will look into it too but I feel that the solution *might* be easier.  @ochawkeye it seems that you have been able to "access" all the games.  Is it possible to attach here the files for weeks 2, 3 and 4? I want to check whether the issue is with corrupted files  as I mentioned in my comment.

**Comment by ochawkeye** [comment]
> g = nflgame.games(2015,week=4,kind="POST")

image

FYI - the Super Bowl was actually played in week 5 in 2015.

I add here all Playoff games from 2015 (4x week 1, 4x week2, 2x week 3, 1x week 5 = 11 total)
[2016010900.json.gz](https://github.com/BurntSushi/nflgame/files/172044/2016010900.json.gz)
[2016020700.json.gz](https://github.com/BurntSushi/nflgame/files/172048/2016020700.json.gz)
[2016012401.json.gz](https://github.com/BurntSushi/nflgame/files/172043/2016012401.json.gz)
[2016012400.json.gz](https://github.com/BurntSushi/nflgame/files/172047/2016012400.json.gz)
[2016011701.json.gz](https://github.com/BurntSushi/nflgame/files/172046/2016011701.json.gz)
[2016011700.json.gz](https://github.com/BurntSushi/nflgame/files/172045/2016011700.json.gz)
[2016011601.json.gz](https://github.com/BurntSushi/nflgame/files/172050/2016011601.json.gz)
[2016011600.json.gz](https://github.com/BurntSushi/nflgame/files/172049/2016011600.json.gz)
[2016011001.json.gz](https://github.com/BurntSushi/nflgame/files/172052/2016011001.json.gz)
[2016011000.json.gz](https://github.com/BurntSushi/nflgame/files/172053/2016011000.json.gz)
[2016010901.json.gz](https://github.com/BurntSushi/nflgame/files/172051/2016010901.json.gz)

**Pull request merged**
