### PR TITLE
Attempt to tag games as "AM" or "PM"

### PR DESCRIPTION
**Pull request by ochawkeye**
Jumping off point for assigning "AM" or "PM" to games in case no one else tackles over the coming week.

### CODE REVIEW

**Comment by BurntSushi** [comment]
This is a good start, but I have two suggestions/questions:

1. Can we leave the `time` field unmodified? Instead, it might be better to add a new field called `meridiem`.
2. The new field `meridiem` can have *three* values: `AM`, `PM` or `None`. Some of your cases call for setting `None`, which more accurately reflects the "unknown" state of things. (I really want to try to avoid labeling a game time `AM`/`PM` unless we're really pretty sure that it is right.)

A simple implementation might actually take two passes through the game data, e.g., on the first pass, label all games we know to be `PM`, which I think includes any game starting between `12` and `8`. (I can't imagine a football game starting between `12AM-8AM EST`.) The second pass could go through and look at games that don't have `meridiem` set yet. The rules might be something like:

1. If the time is `< 12` and there are `PM` games *proceding* that game on the same day (with respect to its `gsis_id`), then it should be classified as `AM`.
2. If the time is `> 12` and there are `PM` games *preceding* that game on the same day (with respect to its `gsis_id`), then it should be classified as `PM`.

This could potentially leave games with a `None` meridiem value. e.g., If a `9:30` game is played on a day where no other games are played.

**Comment by ochawkeye** [comment]
Thanks.  Here's an update based on your feedback.  It does deviate slightly from your suggestion.  Whereas you state "I can't imagine a football game starting between 12AM-8AM EST." (which I agree with), this does leave almost all Monday night and Thursday night games as `None`.  I have widened the "I can't imagine" window from 12AM-9AM EST so all 8:25 and 8:30 games are bucketed as PM games.  My thought process was "No way they would force the west coast to wake up at 5:30AM to watch a football game", though they have done 6:30AM so does seem a rather arbitrary argument.

Maybe instead of making a bigger window I should have just handled Monday & Thursday games explicitly.

**Comment by BurntSushi** [comment]
@ochawkeye Hmm, yeah, that window looks pretty tight to me. I think we should:

1. Shrink that window (say, even, `12-5`).
2. Assume that all games played during the week are always `PM`.
3. Assume that all playoff games are always `PM` (I think these are usually evening games on Saturday/Sunday).

**Comment by ochawkeye** [comment]
That's easy enough to do, though I'm hesitant.  An 11:30 AM EST Thanksgiving game seems plausible.

**Comment by ochawkeye** [comment]
Answered my own question...Just need to let the other rules apply first and only worry about weekday and playoff assumptions if it has still fallen all the way through.

**Comment by BurntSushi** [comment]
Right... Forgot about thanksgiving. Haha. But yeah, thankfully, Thanksgiving has multiple games. :-)

**Comment by ochawkeye** [comment]
With this method, I'm not even sure that a hour constraint need to be applied.  Commenting out lines 84 & 85 should still catch all games (I think)

**Comment by BurntSushi** [comment]
@ochawkeye Really? Aren't those times needed for seeding? e.g., For a 9:30AM game, it needs to be able to find those later PM games, but those later games are only PM if we start with the assumption that `12-5` is always PM, right? Does commenting them out cause no change?

**Comment by ochawkeye** [comment]
No, you're right.  It works *this* week because there is an AM game (it sees there is a later game that "looks like" and earlier start time so assigns that one AM and all of the afternoon games see the earlier game that "looks like" a later start time so assigns those PM), but a week that doesn't have an AM game would be `None` across the board.

My bad.  Definitely need to leave that first pass hour scan window in there.

**Comment by BurntSushi** [comment]
@ochawkeye OK, I buy it. The code is gorgeous, nice work!

**Comment by ochawkeye** [comment]
I really appreciate that.

git101 question - was there I way I could have/should have made the pull request that would have bundled those 5 commits into a single line item so as to obfuscate my ineptitude in trying to piece this together step-by-step?  Or is this a case where once an immature PR gets posted (like 14ed8f9) each subsequent partial commit is going to get documented?

**Comment by BurntSushi** [comment]
@ochawkeye There are two different schools of thought on that. Me personally, I like having PRs squashed into a single commit. You could have done that by rebasing your branch on to master (`git rebase master`), and then *force pushing* it. It would automatically update the PR.

However, another school of thought says that your progress through the change should be recorded.

All in all, I'm not going to make a stink about it for this repo. If we end up some day with lots of contributors, then ya, it might be worth creating a policy or something and following it, but I'm happy to wing it for now. :-)

**Comment by ochawkeye** [comment]
FYI - out of 2312 games in the schedule currently, this leaves 78 preseason and 7 regular season games with unassigned meridiems.

Regular season games:
`2009121900`: `Saturday 8:20`
`2010122500`: `Saturday 7:30`
`2011121700`: `Saturday 8:20`
`2011122500`: `Sunday 8:20`
`2012122200`: `Saturday 8:30`
`2015121900`: `Saturday 8:25`
`2015122600`: `Saturday 8:25`

**Pull request merged**
